- name: bitrix
  hosts: ubuntu1
  tasks:
   - name: install 
     apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
     with_items:
      - git
      - nginx
      - mysql-server
      - php
      - php-mcrypt
      - php-mysql
      - php-gd
      - php-mbstring
      - python-pip
   - name: install python pachacge
     pip: name={{ item }}
     with_items:
      - MySQL-python    
   - name: install apache2
     apt: name={{ item }}
     with_items:
      - libapache2-mod-php
      - apache2
   - name: create dir
     file: path=/var/www/default state=directory owner=www-data group=www-data
   - name: download template
     command: wget https://www.1c-bitrix.ru/download/start_encode_php5.tar.gz creates=start_encode_php5.tar.gz chdir=/var/www/default
   - name: unpack
     command: tar xvfz start_encode_php5.tar.gz creates=index.php chdir=/var/www/default
   - name: create dir
     file: path=/var/www/default state=directory owner=www-data group=www-data recurse=yes
   - name: remove def config
     file:
       path: "/etc/nginx/{{ item }}"
       state: absent
     with_items:
      - sites-enabled/default 
      - nginx.conf
     notify: restart nginx
   - name: copy main config
     template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
     notify: restart nginx
   - name: copy default config
     template: src=templates/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
     notify: restart nginx

   - name: delete default
     file: path={{ item }} state=absent
     with_items:
      - /etc/apache2/sites-enabled/default.conf
     notify: restart apache

   - name: apache2 listen on port 8081
     lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
     notify: restart apache
   - name: change timezone
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^;date.timezone =" line="date.timezone=Europe/Moscow" state=present
     notify: restart apache

   - name: change config2
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^opcache.revalidate_freq=2" line="opcache.revalidate_freq=0" state=present
     notify: restart apache
   - name: change config3
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^;mbstring.func_overload = 0" line="mbstring.func_overload = 2" state=present
     notify: restart apache
   - name: change config4
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^;mbstring.internal_encoding" line="mbstring.internal_encoding = utf-8" state=present
     notify: restart apache
   - name: change config5
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^display_errors = Off"  line="display_errors = On" state=present
     notify: restart apache
   - name: change config6
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^short_open_tag = Off"  line="short_open_tag = On" state=present
     notify: restart apache
   - name: change config7
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^;opcache.max_accelerated_files"  line="opcache.max_accelerated_files=100000" state=present
     notify: restart apache
   - name: change config8
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^; max_input_vars = 1000"  line="max_input_vars = 10000" state=present
     notify: restart apache
   - name: change config9
     lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^upload_max_filesize = 2M"  line="pload_max_filesize = 64M" state=present
     notify: restart apache

   - name: copy config
     template: src=templates/def_apache.conf.j2 dest=/etc/apache2/sites-available/test.conf
     notify: restart apache
   - name: ensite
     command: a2ensite test
   - name: create db
     mysql_db: name=bitrixtest state=present
   - name: create user
     mysql_user: #name=bitrix password=testpass priv:bitrixtest.*:ALL
       name: bitrix
       password: testpass
       priv: bitrixtest.*:ALL
  handlers:
   - name: restart apache
     service: name=apache2 state=restarted
   - name: restart nginx
     service: name=nginx state=restarted 
